"""
Constants to generate different results with different models
"""

WORLD_ETF_TICKERS = ["VWCE.DE", "MSCI", "ACWI"]

PORTFOLIO_INDEX_WEIGHT = 0.8
PORTFOLIO_CRYPTO_WEIGHT = 1 - PORTFOLIO_INDEX_WEIGHT
FUNNEL_APPROACH = False

START_TEST_DATE = 0  # TODO
END_TEST_DATE = 0  # TODO

INITIAL_INVESTMENT = 100
DCA_MONTHLY = 0  # default
